//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourbesCharge.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consommation
    {
        public int IdConsommation { get; set; }
        public System.DateTime DateConsommation { get; set; }
        public int IntervalleCalcul { get; set; }
        public double PuissanceActive { get; set; }
        public double PuissanceReactive { get; set; }
        public string IdCompteur { get; set; }
    
        public virtual Compteur Compteur { get; set; }
    }
}
