//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourbesCharge.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CourbeChargeEntities : DbContext
    {
        public CourbeChargeEntities()
            : base("name=CourbeChargeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CategorieClient> CategorieClient { get; set; }
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<Compteur> Compteur { get; set; }
        public virtual DbSet<Consommation> Consommation { get; set; }
        public virtual DbSet<Contrat> Contrat { get; set; }
        public virtual DbSet<Installation> Installation { get; set; }
        public virtual DbSet<Utilisateur> Utilisateur { get; set; }
    }
}
