//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourbesCharge.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Installation
    {
        public int IdInstallation { get; set; }
        public System.DateTime DateAmenagement { get; set; }
        public string Adresse { get; set; }
        public string IdCompteur { get; set; }
        public int IdContrat { get; set; }
    
        public virtual Compteur Compteur { get; set; }
        public virtual Contrat Contrat { get; set; }
    }
}
